shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('submit', views.submit, name='submit')
]

shop/models.py
from django.db import models
from django.urls import reverse


SIZE_CHOICES = [(j, str(j)) for j in ['Small','Large','Medium']]


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    size = models.CharField(max_length=6, choices=SIZE_CHOICES, default='Medium')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.http import HttpResponse
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

def about(request):
 return render(request,'shop/about.html',{})


def contact(request):
 return render(request,'shop/contact.html',{})

def submit(request):
    name=request.GET['Name']
    print (name)
    message = Mail(
        from_email='from_email@example.com',
        to_emails='nochuba@unomaha.edu',
        subject=name,
        html_content='<strong>and easy to do anywhere, even with Python</strong>')
    try:
        sg = SendGridAPIClient('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')
        response = sg.send(message)
        if response.status_code == 202:
            print('email sent')
        else:
            print(response.status_code)
            print(response.body)
            print(response.headers)
    except Exception as e:
        print(str(e))
    return render(request, 'shop/contact.html', {})

shop/templates/shop/about.html

<div class="nav">
    {% extends "shop/base.html" %}
</div>
{% load static %}
<!DOCTYPE html>
<html>
{% block content %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
    height: 100%;
}
h1, h2, h3, h4 {
    font-family: 'Lobster', cursive;
}
.parallax {
    /* The image used */
    /* Full height */
    height: 100%;
    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
/* Turn off parallax scrolling for tablets and phones. Increase the pixels if needed */
@media only screen and (max-device-width: 1366px) {
    .parallax {
        background-attachment: scroll;
    }
}
</style>
</head>
<body>

<h1><p align="center">The Little Things is an online food delivery service opened in 2005. At The Little Things.com, our focus is providing delicious meals at reasonable prices.
    Our menu offers an impressive array of foods including sandwiches, soups, salads, and healthy desserts. Our ordering process is simple to use, and satisfaction is guaranteed with every order delivery. Stop by our site
    today to experience exceptional cuisine!</p></h1>




</body>
{% endblock %}
</html>

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}The Little Things {% endblock %}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="{% static "css/base.css" %}" rel="stylesheet">
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>


<body>
  <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <a class="navbar-brand" href="#">The Little Things</a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url "shop:about" %}">About Us</a></li>
                    <li><a href="{% url "shop:product_list" %}">Menu</a></li>
                    <li><a href="{% url "shop:contact" %}">Contact Us</a></li>
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories
                        <span class="caret"></span></a>
                           <ul class="dropdown-menu">
                               {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                                </li>
                              {% endfor %}
                             {% comment %} <li><a href="#">Salads</a></li>
                              <li><a href="#">Sandwiches</a></li>
                              <li><a href="#">Soups</a></li>{% endcomment %}
                           </ul>
                    </li>
                </ul>


				<ul class="nav navbar-right navbar-nav">
                    <li><!-- Search -->
				        <form class="navbar-form" role="search">
					        <div class="form-group">
						        <input type="text" class="form-control">
					        </div>
					    <button type="submit" class="btn btn-default">Search</button>
				        </form>
                    </li>
                    <li>
                       <div class="cart ">
                            {% with total_items=cart|length %}
                                {% if cart|length > 0 %}
                                    Your cart:
                                    <a href="{% url "cart:cart_detail" %}">
                                    {{ total_items }} item{{ total_items|pluralize }},
                                    ${{ cart.get_total_price }}
                                    </a>
                                {% else %}
                                    Your cart is empty.
                                {% endif %}

                            {% endwith %}
                        </div>
                    </li>
                </ul>




            </div>

            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

	<div class="jumbotron feature">
		<div class="container">

			<h1><span class="glyphicon glyphicon-equalizer"></span> Enjoy the little things</h1>
			<p>Share the little love...</p>

		</div>
	</div>

    <!-- Content -->
    <div class="container">

  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>


<footer>

</footer>

</html>

shop/templates/shop/contact.html

<div class="nav">
    {% extends "shop/base.html" %}
</div>
{% load static %}
<!DOCTYPE html>
<html>
{% block content %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
    height: 100%;
}
h1, h2, h3, h4 {
    font-family: 'Lobster', cursive;
}
.parallax {
    /* The image used */
    /* Full height */
    height: 100%;
    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
/* Turn off parallax scrolling for tablets and phones. Increase the pixels if needed */
@media only screen and (max-device-width: 1366px) {
    .parallax {
        background-attachment: scroll;
    }
}
</style>
</head>
<body>

<h1><p align="center">Feel free to get in touch with us!!</p></h1>



<h2><p align="center">Give us a call +1 713 8945567 </p></h2>
<h2><p align="center">or</p></h2>
<h2><p align="center">Shoot us a mail to little@gmail.com </p></h2>
<form action="/submit">
    Email:
    <input type="text" name="Name">
    <input type="submit" value="Send">
</form>
<div class="parallax"></div>

</body>
{% endblock %}
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}"></a></h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
  {{ cart_product_form }}
  {% csrf_token %}
  <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}
  </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Menu{% endif %}
{% endblock %}

{% block content %}

  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}
    {% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}
            {% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>
{% endblock %}